import { z } from 'zod';

export const monsterSchema = z.object({
  id: z.string().min(1, 'ID is required'),
  name: z.string().min(1, 'Name is required'),
  size: z.enum(['Fine', 'Diminutive', 'Tiny', 'Small', 'Medium', 'Large', 'Huge', 'Gargantuan', 'Colossal']),
  type: z.string().min(1, 'Type is required'),
  subtypes: z.array(z.string()).default([]),
  hitDice: z.string().min(1, 'Hit dice is required'),
  hitPoints: z.number().optional(),
  initiative: z.number(),
  speed: z.object({
    land: z.string().optional(),
    fly: z.string().optional(),
    swim: z.string().optional(),
    climb: z.string().optional(),
    burrow: z.string().optional(),
    other: z.string().optional(),
  }),
  armorClass: z.object({
    total: z.number(),
    touch: z.number(),
    flatFooted: z.number(),
    modifiers: z.string().optional(),
  }),
  baseAttack: z.number(),
  grapple: z.number(),
  attack: z.string().optional(),
  fullAttack: z.string().optional(),
  space: z.string().min(1, 'Space is required'),
  reach: z.string().min(1, 'Reach is required'),
  specialAttacks: z.array(z.string()).default([]),
  specialQualities: z.array(z.string()).default([]),
  saves: z.object({
    fortitude: z.number(),
    reflex: z.number(),
    will: z.number(),
  }),
  abilities: z.object({
    strength: z.number().or(z.literal('—')),
    dexterity: z.number().or(z.literal('—')),
    constitution: z.number().or(z.literal('—')),
    intelligence: z.number().or(z.literal('—')),
    wisdom: z.number().or(z.literal('—')),
    charisma: z.number().or(z.literal('—')),
  }),
  skills: z.record(z.string(), z.number()).default({}),
  feats: z.array(z.string()).default([]),
  environment: z.string().optional(),
  organization: z.string().optional(),
  challengeRating: z.string().min(1, 'Challenge rating is required'),
  treasure: z.string().optional(),
  alignment: z.string().optional(),
  advancement: z.string().optional(),
  levelAdjustment: z.string().optional(),
  description: z.string().min(1, 'Description is required'),
  combatSection: z.string().optional(),
  specialAbilityDescriptions: z.record(z.string(), z.string()).default({}),
  tags: z.array(z.string()).default([]),
  status: z.enum(['draft', 'review', 'complete']).default('draft'),
  notes: z.string().optional(),
});

export type Monster = z.infer<typeof monsterSchema>;
